### ISSUE TITLE
`Core.Typeof` instead of `instance_type`?

### ISSUE THREAD

**Issue by cscherrer** [dfdx/Yota.jl#109]
https://github.com/dfdx/Yota.jl/pull/108#event-6403229303 was just merged (thanks!), but in https://github.com/cscherrer/KeywordCalls.jl/pull/30, @simeonschaub points out that `Core.Typeof` could serve the same purpose. I haven't tried it yet, but his comment makes me wonder if that's also a better approach for Yota.

**Comment by dfdx** [comment]
`Core.Typeof` was also the solution for several issues with `Expr(:static_parameter, ...)` in Umlaut, so it's a double hit. Thank you!
