### ISSUE TITLE
Tape BoundsError using dictionaries

### ISSUE THREAD

**Issue by MikeInnes** [dfdx/Yota.jl#34]
```julia
julia> d = Dict()
Dict{Any,Any} with 0 entries

julia> grad(5) do x
         d[:x] = x
         d[:x] * d[:x]
       end
ERROR: BoundsError: attempt to access 8-element Array{Yota.AbstractOp,1} at index [-1]
```

**Comment by dfdx** [comment]
Unfortunately, Yota is not supposed to work with mutating operations (except for a limited list of known functions that are converted to non-mutating before processing). May I ask what's the use case for this example? Or are you just examining Cassette-based tracer to incorporate something similar to Zygote?

**Comment by MikeInnes** [comment]
No particular use case, only curious how this would behave. I'm a bit surprised you wouldn't want to support this, as it's the kind of thing that a tracing AD can support quite well just by ignoring these operations (compared to a source approach which has to deal with them explicitly).

If that's the case though, fine to interpret this as a docs / error messages issue.
