### ISSUE TITLE
Can't use Keyword Arguments

### ISSUE THREAD

**Issue by Sagimusume** [dfdx/Yota.jl#37]
```Julia
julia> mutable struct Linear{T}
         W::AbstractArray{T,2}
         b::AbstractArray{T}
       end

julia> f(x;w,b) = w*x .+ b
f (generic function with 2 methods)

julia> (l::Linear)(x) = f(x,w=l.W,b=l.b)

julia> m1 = Linear(rand(3,4), rand(3));

julia> X = rand(4,5);

julia> loss(X,m1) = sum(m1(X));

julia> val, g = grad(loss, X,m1)
ERROR: MethodError: no method matching NamedTuple{(:w, :b),Tuple{Array{Float64,2},Array{Float64,1}}}(::Array{Float64,2}, ::Array{Float64,1})
```

**Comment by dfdx** [comment]
Internal representation of keyword parameters in Julia is somewhat weird, so tools like Cassette (which we heavily rely on for tracing) has very limited support for them. I'll check what exactly is going on here, but is there any particular reason to use keyword args in this example?

**Comment by Sagimusume** [comment]
I wanted to use it because I thought it could be used casually because NNlib's conv function used keyword arguments.  Thank you

**Comment by dfdx** [comment]
It should be possible to use keyword arguments in this case, though it might require changes in NNlib itself. For example, we support keyword version of `sum()` pretty well:

```
julia> loss(X) = sum(X, dims=1)[1]
loss (generic function with 1 method)

julia> _, g = grad(loss, rand(3,4))
(0.864974962343517, GradResult(1))

julia> g[1]
3×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0
```
During Julia compilation-execution loop call to `sum(x, dims=1)` is actually transformed into call to `Base._sum(x, dims)` which we intercept, and we successfully continue with differentiation. I believe there's nothing stopping us from doing the same thing for NNlib's `conv()` except for artificial constraints. 

Let me play around with it for a few days.

**Comment by dfdx** [comment]
A few days turned to be four months, but this issue is finally fixed! Currently master branch of Yota uses JuliaInterpreter instead of Cassette to trace code which allows much better control over functions with keyword arguments. The docs are on the way, but the code from the first post works as is.
