### ISSUE TITLE
Propagate zero derivative indicator

### ISSUE THREAD

**Issue by dfdx** [dfdx/Yota.jl#63]
Motivating example is RNN which returns a tuple of `(last_hidden, all_hiddens)`, but usually only one of these is actually used in further computations. In such settings, gradient w.r.t. to non-target element of the tuple can be replaced with some kind of symbolic zero instead of actually allocated object.

**Comment by oxinabox** [comment]
This is one of the reasions ChainRulesCore has `AbstractZero` and its subtypes.

**Comment by dfdx** [comment]
Yep! Again, it's already integrated in #70, this issue will be closed as soon as that PR is merged.
