### ISSUE TITLE
Use Zero(), One() and Composite() from ChainRules.jl

### ISSUE THREAD

**Issue by dfdx** [dfdx/Yota.jl#64]
Of these 3, most promising is `Composite`, which might be a simpler replacement for the current complicated derivative propagation through struct fields. 
However it's unclear if combining instances of `Composite` will fit into implementation of `var -> grad var` mechanism.

**Comment by oxinabox** [comment]
@willtebbutt and I have debated removing `One()` for ages.
You might like to share your thoughts.
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/62


>  However it's unclear if combining instances of Composite will fit into implementation of `var -> grad var` mechanism.

I don't understand what you are saying but I am happy to clarify anything you need clarified.

**Comment by dfdx** [comment]
In #70 (which is blocked by unrelated stuff, but otherwise ready to be merged) I ended up using `Zero()` and `Composite()`, but not `One()`. For `One()` I just didn't find a proper use, so can't really comment on this yet. Anyway, thanks for letting me know about this discussion, it will definitely influence further development!

**Comment by dfdx** [comment]
By the way, thanks for `Composite{T}`! I had something similar from the very beginning, but couldn't come up with the proper design. Using `ChainRulesCore.Composite{T}` fixed several most ugly parts of the codebase, so it has been one of the two coolest improvements in the last 6 months!
